[build]
command = "hugo --gc --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.147.1"
GO_VERSION = "1.24.2"
NODE_VERSION = "22"
TZ = "UTC"

[context]
[context.branch-deploy]
command = "hugo --gc --minify -F -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo --gc --minify -F -b $DEPLOY_PRIME_URL"

[context.production]
command = "hugo --gc --minify"

[context.production.environment]
HUGO_ENV = "production"
